# Generated by Django 2.2.7 on 2019-12-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Open', models.DateField()),
                ('Close', models.DateField()),
                ('Salary', models.IntegerField()),
                ('Categories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Birthday', models.DateField()),
                ('Contact_number', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Skills', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Status', models.CharField(max_length=255)),
                ('Company_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('Job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saved', models.IntegerField()),
                ('Company_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('Job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='Job_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job'),
        ),
    ]
